name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo con submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.117.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public          # carpeta generada por Hugo
          publish_branch: gh-pages       # rama donde se sirve el sitio
          force_orphan: true             # historial limpio
          enable_jekyll: false           # ← genera .nojekyll